### PR TITLE
add Lucas (page.devlucas.page)

### PR DESCRIPTION
**Pull request by LucasHT22**

### CODE REVIEW

**Comment by iUnstable0** [comment]
you should add / to the end of your url

**Comment by LucasHT22** [comment]
Wdym?

**Comment by iUnstable0** [comment]
it should be url: "https://yourdomain.tld/" not "https://yourdomain.tld"
i explained the reason on another pull request

**Comment by iUnstable0** [comment]
this is the link https://github.com/hackclub/webring/pull/81
also idk why on my pull request it said all checks failed

**Pull request merged**
