### PR TITLE
Add Kokonico to members.json

### PR DESCRIPTION
**Pull request by Kokonico**
I would like to be added to the hack club web ring, you can verify I'm in the slack by looking for @Kokonico (or KKNC) within it.

### CODE REVIEW

**Review by kirby-b — APPROVED** [review]
I don't have write access as far as I am aware, but hopefully my comment on this will bring attention back to this repo.

**Comment by Shrey-Mehra** [comment]
Hey @Kokonico , did you add the HTML code to your site as I am looking on your site so webring isn't present anywhere

**Comment by Kokonico** [comment]
Oh sorry! Didn't see your comment. I'll add the code to the website in a few hours.

**Comment by Shrey-Mehra** [comment]
Hey @Kokonico , will Wait till today for changes

**Comment by Kokonico** [comment]
hello, I have added the changed to my website.

sorry it took so long! my footer code is weird, so I needed to inject the js after the badge 🫠

**Review by Shrey-Mehra — APPROVED** [review]
cool you have done from your End. I'm merging the pull request as everything looks fine to me

**Comment by Kokonico** [comment]
I forgot to add a comma in the members.json file 😭, can you fix that?

**Comment by Shrey-Mehra** [comment]
But your site is looking well to me

**Comment by Kokonico** [comment]
It's not the site that's the problem. It's the actual file in this repository that I edited. I forgot to put a comma before putting my entry.

**Pull request merged**
