### PR TITLE
add my website to the list

### PR DESCRIPTION
**Pull request by kevadesu**

### CODE REVIEW

**Review by krishstwt — CHANGES_REQUESTED** [review]
Hey 👋 

Your PR looks great, but there are some merge conflicts, could you please resolve them so that we can merge this? 

Here are docs on how to do that: [github docs](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github)

Please let me know if you need any problems 😄

**Comment by ni5arga** [comment]
I've fixed the conflict.

**Review by ni5arga — APPROVED** [review]

**Review by krishstwt — APPROVED** [review]
Looks good

**Comment by ni5arga** [comment]
I don't think the change was deployed on Vercel. His URL hasn't appeared on site.

**Pull request merged**
