### PR TITLE
Main

### PR DESCRIPTION
**Pull request by iUnstable0**
i explained the issue with slash at the end of url before

https://github.com/hackclub/webring/pull/81#issue-1512792572

also i edited to add my new domain (replacing biggybig.xyz)

### CODE REVIEW

**Review by xkrishguptaa — COMMENTED** [review]
Don't you think adding them programmatically would be better? just a suggestion though

**Comment by iUnstable0** [comment]
yeah i'll do that later

**Comment by iUnstable0** [comment]
wait nevermind someone edited the embed.js and made it check hostname instead of href so that shouldn't;t be an issue now

**Comment by iUnstable0** [comment]
looks like someone forgot to update embed.min.js

**Pull request merged**
