### PR TITLE
Requesting permission to join.

### PR DESCRIPTION
**Pull request by Kirito139**
My slack handle is roguewielder

### CODE REVIEW

**Review by Shrey-Mehra — APPROVED** [review]
Everthing Looks Great to me. Merging this Pull Request

**Comment by Kirito139** [comment]
Yay! Anything else I need to do now?

**Comment by Shrey-Mehra** [comment]
Nope just keep HackClub tag on your site and everything will good 😄

**Comment by Kirito139** [comment]
Hmm... my site isn't showing up on the homepage, and as far as I can tell it's not in the loop. Also, some members don't have it on their sites, or just have flat-out non-accessible sites, breaking the loop.

**Comment by Shrey-Mehra** [comment]
Ok thanks Lennier for letting me know I'll look into it

**Pull request merged**
