### PR TITLE
Remove Reese Armstrong

### PR DESCRIPTION
**Pull request by reesericci**
I am no longer participating in the Hack Club webring

### CODE REVIEW

**Review by kirby-b — APPROVED** [review]
I am not honestly sure if I can approve this, but I see nothing wrong here. Maybe me commenting will bring attention back to this repo

**Review by Shrey-Mehra — APPROVED** [review]
Hey @reesericci , I'm approving this Pull Request.

**Comment by reesericci** [comment]
many are saying this

**Comment by Shrey-Mehra** [comment]
Your pull request has been merged

**Pull request merged**
